# Generated by Django 5.2.11 on 2026-03-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_rename_uploaded_at_file_imported_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(max_length=20),
        ),
    ]
